#pragma once

/** Elysium-style HUD CSS + byline for WiFiManager portal pages. */
constexpr char kPortalHeadHtml[] =
    "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">"
    "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>"
    "<link href=\"https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Orbitron:wght@600;800&display=swap\" rel=\"stylesheet\">"
    "<style>"
    ":root{--amber:#FF9F1C;--amber-bright:#FFB703;--amber-dim:#B57317;--void:#050505;"
    "--surface:rgba(255,159,28,.05);--border:rgba(255,159,28,.32);--border-strong:rgba(255,159,28,.65)}"
    "html,body{background:var(--void)!important;color:var(--amber)!important;"
    "font-family:'JetBrains Mono',ui-monospace,Menlo,Consolas,monospace!important;"
    "text-align:center;margin:0;min-height:100%;"
    "background-image:radial-gradient(ellipse at top,rgba(255,159,28,.07),transparent 55%),"
    "radial-gradient(ellipse at bottom right,rgba(217,4,41,.04),transparent 50%)!important;"
    "background-attachment:fixed}"
    "body::before{content:'';position:fixed;inset:0;pointer-events:none;z-index:9000;"
    "background:repeating-linear-gradient(to bottom,rgba(255,159,28,.05) 0 1px,transparent 1px 3px);"
    "mix-blend-mode:screen;opacity:.45}"
    "body::after{content:'';position:fixed;inset:0;pointer-events:none;z-index:8999;"
    "background:radial-gradient(ellipse at center,transparent 50%,rgba(0,0,0,.55) 100%)}"
    ".wrap{position:relative;text-align:left;display:inline-block;min-width:260px;max-width:520px;"
    "width:100%;margin:1.5rem auto;padding:1.25rem 1.15rem 1.4rem;box-sizing:border-box;"
    "background:linear-gradient(180deg,rgba(255,159,28,.04),rgba(255,159,28,.015)),rgba(5,5,5,.9);"
    "border:1px solid var(--border);"
    "clip-path:polygon(14px 0,100% 0,100% calc(100% - 14px),calc(100% - 14px) 100%,0 100%,0 14px)}"
    "@media (max-width:640px){"
    ".wrap{display:block!important;min-width:0!important;max-width:none!important;width:100%!important;"
    "margin:0!important;padding:1rem .85rem 1.25rem!important;"
    "border-left:0!important;border-right:0!important;clip-path:none!important}"
    "body{padding:0!important}"
    "}"
    ".wrap::before,.wrap::after{content:'';position:absolute;width:10px;height:10px;border-color:var(--amber)}"
    ".wrap::before{top:6px;left:6px;border-top:1px solid;border-left:1px solid}"
    ".wrap::after{bottom:6px;right:6px;border-bottom:1px solid;border-right:1px solid}"
    "h1{font-family:Orbitron,'JetBrains Mono',monospace!important;font-size:1.15rem!important;"
    "letter-spacing:.28em;text-transform:uppercase;color:var(--amber)!important;"
    "text-shadow:0 0 8px rgba(255,159,28,.55),0 0 18px rgba(255,159,28,.25);margin:.2rem 0 .4rem}"
    "h2,h3{font-family:Orbitron,'JetBrains Mono',monospace;letter-spacing:.2em;text-transform:uppercase;"
    "font-size:.85rem;color:var(--amber);margin:1rem 0 .5rem}"
    ".wm-byline{margin:.15rem 0 1.1rem;color:var(--amber-dim)!important;font-size:.68rem;"
    "letter-spacing:.22em;text-transform:uppercase;font-weight:400!important;opacity:1}"
    "div,input,select,label,p,dt,dd,td,th,small{color:var(--amber);font-family:inherit}"
    "label,dt,.msg h4{font-size:.68rem;letter-spacing:.22em;text-transform:uppercase;color:var(--amber-dim)!important}"
    "p,dd,td,small,.msg{font-size:.78rem;letter-spacing:.04em;color:var(--amber)!important}"
    "a{color:var(--amber-bright)!important;font-weight:500;text-decoration:none;letter-spacing:.08em}"
    "a:hover{color:#fff!important;text-shadow:0 0 8px rgba(255,159,28,.7)}"
    "input,select,textarea{background:var(--surface)!important;border:1px solid var(--border)!important;"
    "border-radius:0!important;color:var(--amber)!important;padding:10px!important;width:100%;"
    "box-sizing:border-box;outline:none;font-family:inherit;font-size:.8rem!important;margin:6px 0}"
    "input:focus,select:focus{border-color:var(--amber)!important;box-shadow:0 0 0 1px var(--amber)}"
    "input[type=radio],input[type=checkbox]{width:auto!important;accent-color:var(--amber)}"
    "button,input[type=button],input[type=submit]{background:rgba(255,159,28,.08)!important;"
    "border:1px solid var(--border-strong)!important;border-radius:0!important;color:var(--amber)!important;"
    "line-height:2.2rem;font-size:.72rem!important;letter-spacing:.2em;text-transform:uppercase;"
    "font-family:inherit;width:100%;cursor:pointer;margin:8px 0;"
    "clip-path:polygon(8px 0,100% 0,100% calc(100% - 8px),calc(100% - 8px) 100%,0 100%,0 8px);"
    "transition:background-color .15s,color .15s;opacity:1!important}"
    "button:hover,input[type=button]:hover,input[type=submit]:hover{"
    "background:var(--amber)!important;color:var(--void)!important}"
    "button.D,button.D:hover{background:rgba(217,4,41,.15)!important;border-color:#D90429!important;"
    "color:#ff6b81!important}"
    "button:active{opacity:.7!important}"
    ".msg{background:rgba(255,159,28,.05)!important;border:1px solid var(--border)!important;"
    "border-left:3px solid var(--amber)!important;border-radius:0!important;color:var(--amber)!important;"
    "padding:14px;margin:14px 0;text-align:left}"
    ".msg.P{border-left-color:var(--amber-bright)!important}"
    ".msg.P h4{color:var(--amber-bright)!important}"
    ".msg.D{border-left-color:#D90429!important}"
    ".msg.D h4{color:#ff6b81!important}"
    ".msg.S{border-left-color:#5cb85c!important}"
    ".msg.S h4{color:#8dff9a!important}"
    "hr{border:0;border-top:1px solid var(--border);margin:1rem 0}"
    "table{width:100%;border-collapse:collapse;font-size:.75rem}"
    "th,td{border-bottom:1px solid rgba(255,159,28,.15);padding:6px 4px;text-align:left}"
    ".q[role=img]{-webkit-filter:invert(1) sepia(1) saturate(5) hue-rotate(5deg);filter:invert(1) sepia(1) saturate(5) hue-rotate(5deg)}"
    ".hud-home{margin:10px 0;padding:10px;border:1px solid rgba(255,159,28,.2);background:rgba(255,159,28,.03);"
    "font-size:.72rem;letter-spacing:.12em;color:var(--amber-dim)}"
    ".hud-home b{color:var(--amber);font-weight:500}"
    "input:disabled,select:disabled{opacity:.4;cursor:not-allowed}"
    ".msg.flash{animation:hudFade 1.6s ease forwards}"
    "@keyframes hudFade{0%,55%{opacity:1}100%{opacity:0;height:0;margin:0;padding:0;border:0}}"
    "body.invert,body.invert a,body.invert h1{background-color:transparent!important;color:var(--amber)!important}"
    "body.invert .msg{background:rgba(255,159,28,.05)!important;border-color:var(--border)!important}"
    "</style>"
    "<script>"
    "function syncHomeCoords(){"
    "var h=document.getElementById('use_home');"
    "var lat=document.getElementById('radar_lat');"
    "var lon=document.getElementById('radar_lon');"
    "if(!h||!lat||!lon)return;"
    "var off=!!h.checked;lat.disabled=off;lon.disabled=off;"
    "}"
    "document.addEventListener('DOMContentLoaded',function(){"
    "var h1=document.querySelector('h1');"
    "if(h1&&/setup saved/i.test(h1.textContent||'')){"
    "location.replace('/param#saved');return;"
    "}"
    "if(h1&&!document.querySelector('.wm-byline')){"
    "var p=document.createElement('p');"
    "p.className='wm-byline';"
    "p.textContent='// BY TOM HUGHES';"
    "h1.insertAdjacentElement('afterend',p);"
    "}"
    "if(location.hash==='#saved'){"
    "var wrap=document.querySelector('.wrap');"
    "if(wrap){"
    "var m=document.createElement('div');"
    "m.className='msg S flash';"
    "m.textContent='Saved';"
    "wrap.insertBefore(m,wrap.children[1]||null);"
    "}"
    "history.replaceState(null,'',location.pathname);"
    "}"
    "var h=document.getElementById('use_home');"
    "if(h){h.addEventListener('change',syncHomeCoords);syncHomeCoords();}"
    "});"
    "</script>";
